### ISSUE TITLE
Unable to create HTTPS-only customer origin

### ISSUE THREAD

**Issue by Sidewinder53** [EdgeCast/terraform-provider-edgecast#94]
### Description
With v0.5.1 when creating a new resource of type `edgecast_orgin`, the parameters `load_balancing_scheme_http` and `load_balancing_scheme_https` are both required, otherwise a "Missing required argument" error is thrown.

When both parameters are defined, but the resource only contains `origin_hostname_https` definitions, applying the configuration fails with an error from the Edgecast API:
```
Error: AddOrigin: SubmitRequest: sendRequest failed (HTTP StatusCode:400): {"Message":"HttpHostnames: This list should have at least a host name for this media type. "}
```

My understanding is, that this makes it impossible to create a customer origin group with HTTPS-only origins. Since it is possible to create such a origin group via the Edgecast UI, I consider this to be a bug.

Could you please clarify if this is the case or if there is a misunderstanding on my side?

### Steps to reproduce
Apply below resource definition to an Edgecast MCC and observe the API error returned.

### Resource definition
```
resource "edgecast_origin" "customer_origin_group_one" {
  account_number              = var.edgecast_account_number
  directory_name              = "customer-origin-one"
  host_header                 = "example.com"
  media_type_id               = 14
  network_configuration       = 1
  follow_redirects            = false
  validation_url              = "https://example.com/keepalive.gif"
  load_balancing_scheme_http = "PF" # RR: Round Robin  PF: Primary/Failover.
  load_balancing_scheme_https = "PF"
  origin_hostname_https {
    name       = "https://example.com:443"
    is_primary = 1
    ordinal    = 0
  }
}
```

**Comment by ssaluja4** [comment]
Thanks for posting the issue. Our team is investigating, and we will provide an update here soon.

**Comment by ssaluja4** [comment]
v0.5.2 fixes this issue, and is available now. Thanks.
